[wokwi]
version = 1
elf = ".pio/build/esp32/firmware.elf"
firmware = ".pio/build/esp32/firmware.bin"

# Forward http://localhost:3000 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:3000"
to = "target:80"
